"""Derive an inertia tensor for the FT Explorer from a distributed shell model.

Why this exists
---------------
``cg_layout.py`` and the ``MassProp`` run inside ``ft_explorer_sport.vspscript``
both represent the 334 g airframe structure as a *single point mass* on the
centreline.  A point contributes nothing to the inertia about its own axes, so
the roll inertia those models report is essentially just the two aileron servos
at +/-11.811 in:

    Ixx = 3.189 kg.in^2, of which the two servos supply 2.533 (79%)

That is not a flight-dynamics inertia.
This script replaces the point with foam-board *shells* laid over the wing,
tails, fuselage and boom, and lets OpenVSP integrate the tensor over the real
geometry.

The model, and its one free constant
------------------------------------
Foam-board aircraft are single-skin shells, so the board area used to build a
component is close to that component's wetted area.  The structure is therefore
modelled as one uniform areal density over all six surfaces, and its value is
*calibrated* rather than imported: it is solved so the shells total the same
334 g residual the BOM already carries.  That residual is itself calibrated
against the supplier's measured 493 g stock airframe, so the total mass stays
anchored to a measurement and only the *distribution* is new information.

Consequence, and why the battery moves
--------------------------------------
Spreading 334 g from one point over the airframe moves the CG.  The 57 mm CG is
a supplier specification and the aero tables in ``aero/`` were generated at it,
so the CG is held fixed and the battery position is re-solved instead.  That
keeps the coefficient set valid and makes the battery location the thing this
script reports as changed.

Passes
------
Each pass is a real OpenVSP solve, kept under ``inertia/`` for traceability.

    A  Mass_Area = 1 on every surface, so each component's reported "mass"
       is its wetted area.  Gives the calibration denominator.
    B  Calibrated areal density, battery mass zeroed.  Gives the mass and CG
       of everything except the battery, which closes the battery solve.
    C  Battery at the solved station.  The result: CG back on 57 mm, and the
       distributed inertia tensor.

Run with:  python shell_inertia.py
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VSP_DIR = Path(os.environ.get("OPENVSP_DIR", r"C:/OpenVSP-3.51.2-win64"))
VSPSCRIPT = VSP_DIR / "vspscript.exe"
MODEL = HERE / "ft_explorer_sport.vsp3"
WORK = HERE / "inertia"

# Geometry that is built out of foam board and therefore carries structure mass.
SHELL_GEOMS = (
    "ForwardFuselage_APPROX",
    "TailBoom_APPROX",
    "PusherMotorPod_APPROX",
    "SportWingRecon",
    "HorizTailEst",
    "VertTailEst",
)

STRUCTURE_PM = "MASS_Airframe_Structure"
BATTERY_PM = "MASS_Battery_4000mAh_3S"

STRUCTURE_KG = 0.3340          # the BOM residual these shells replace
BATTERY_KG = 0.2920
WING_LE_IN = 10.5              # nose-referenced, from ft_explorer_sport.vspscript
TARGET_CG_MM = 57.0            # supplier spec, aft of the wing leading edge
IN2M = 0.0254


# --------------------------------------------------------------------------
# vspscript generation
# --------------------------------------------------------------------------

SCRIPT_TEMPLATE = """\
// GENERATED by shell_inertia.py -- pass {pass_id}.  Do not edit by hand.
//
// Structure is modelled as a uniform foam-board shell over every built
// surface, at {mass_area:.10e} kg/in^2, replacing the single centreline point
// mass the layout model used.

void main()
{{
    ClearVSPModel();
    ReadVSPFile( "{model}" );

    array<string> gids = FindGeoms();
    for ( uint i = 0; i < gids.length(); i++ )
    {{
        string nm = GetGeomName( gids[i] );

{shell_block}
        // The point mass these shells replace.
        if ( nm == "{structure_pm}" )
        {{
            SetParmVal( gids[i], "PointMass", "Mass_Props", 0.0 );
        }}

        if ( nm == "{battery_pm}" )
        {{
            SetParmVal( gids[i], "PointMass", "Mass_Props", {battery_kg:.10e} );
            SetParmVal( gids[i], "X_Rel_Location", "XForm", {battery_x:.10e} );
        }}
    }}

    Update();

    SetAnalysisInputDefaults( "MassProp" );
    string rid = ExecAnalysis( "MassProp" );
    PrintResults( rid );

    while ( GetNumTotalErrors() > 0 )
    {{
        ErrorObj err = PopLastError();
        Print( err.GetErrorString() );
    }}
}}
"""

SHELL_BLOCK = """\
        if ( {cond} )
        {{
            SetParmVal( gids[i], "Shell_Flag", "Mass_Props", 1.0 );
            SetParmVal( gids[i], "Mass_Area", "Mass_Props", {mass_area:.10e} );
            SetParmVal( gids[i], "Density", "Mass_Props", 0.0 );
        }}
"""


def write_script(path: Path, pass_id: str, mass_area: float,
                 battery_kg: float, battery_x_in: float) -> Path:
    cond = " || ".join(f'nm == "{g}"' for g in SHELL_GEOMS)
    shell_block = SHELL_BLOCK.format(cond=cond, mass_area=mass_area)
    path.write_text(
        SCRIPT_TEMPLATE.format(
            pass_id=pass_id,
            model=MODEL.name,
            shell_block=shell_block,
            structure_pm=STRUCTURE_PM,
            battery_pm=BATTERY_PM,
            battery_kg=battery_kg,
            battery_x=battery_x_in,
            mass_area=mass_area,
        ),
        encoding="utf-8",
    )
    return path


# --------------------------------------------------------------------------
# running and parsing
# --------------------------------------------------------------------------

def run_pass(pass_id: str, mass_area: float, battery_kg: float,
             battery_x_in: float) -> dict:
    """Run one MassProp solve in its own directory and parse the result."""
    d = WORK / f"pass_{pass_id}"
    d.mkdir(parents=True, exist_ok=True)
    shutil.copy2(MODEL, d / MODEL.name)
    script = write_script(d / f"pass_{pass_id}.vspscript", pass_id, mass_area,
                          battery_kg, battery_x_in)

    proc = subprocess.run(
        [str(VSPSCRIPT), "-script", script.name],
        cwd=d, capture_output=True, text=True,
    )
    (d / "run.log").write_text(proc.stdout + proc.stderr, encoding="utf-8")

    out = d / f"{MODEL.stem}_MassProps.txt"
    if not out.exists():
        raise RuntimeError(
            f"pass {pass_id}: OpenVSP wrote no MassProps file.\n"
            f"stdout/stderr in {d / 'run.log'}"
        )
    return parse_massprops(out)


def parse_massprops(path: Path) -> dict:
    """Pull the totals and the per-component table out of a MassProps file.

    OpenVSP reports the total inertia about the CG, in kg.in^2 for a model whose
    geometry is in inches and whose masses are in kg.  That was verified against
    a hand-computed parallel-axis sum of the 16 point masses, which reproduces
    the reported Ixx of 3.189366973428757 exactly.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    res: dict = {"components": {}}
    for i, ln in enumerate(lines):
        if ln.endswith("Total Mass"):
            res["mass_kg"] = float(ln.split()[0])
        elif ln.endswith("Center of Gravity"):
            res["cg_in"] = [float(v) for v in ln.split()[:3]]
        elif "Ixx, Iyy, Izz" in ln:
            res["Ixx"], res["Iyy"], res["Izz"] = [float(v) for v in ln.split()[:3]]
        elif "Ixy, Ixz, Iyz" in ln:
            res["Ixy"], res["Ixz"], res["Iyz"] = [float(v) for v in ln.split()[:3]]

    # Per-component table: the block that follows the first tab-separated header.
    start = next(i for i, ln in enumerate(lines) if ln.startswith("Name\tMass"))
    for ln in lines[start + 1:]:
        if not ln.strip() or ln.startswith("Name\t") or ln.startswith("Totals"):
            if ln.startswith("Totals") or ln.startswith("Name\t"):
                break
            continue
        f = ln.split("\t")
        if len(f) < 12:
            continue
        res["components"][f[0]] = {"mass": float(f[1]), "volume": float(f[11])}
    return res


# --------------------------------------------------------------------------
# frame and sign conventions
# --------------------------------------------------------------------------

def to_body_matrix(r: dict) -> dict:
    """Convert an OpenVSP MassProp result into a Simulink 6DOF inertia matrix.

    Two separate conversions happen here, and conflating them is an easy way to
    get a plausible, wrong tensor.

    1. OpenVSP reports *products of inertia*, P = sum(m*x*z), NOT the inertia
       matrix entries.  Verified: for the point-mass configuration it reports
       Ixz = 1.8149, and a hand-computed sum(m*dx*dz) over the 16 point masses
       about the CG gives +1.8148.  The Simulink 6DOF EoM block wants the
       matrix J with H = J*omega, whose off-diagonals are -P.
       (Note ``cg_layout.py`` already negates, so its Ixz has the opposite sign
       to OpenVSP's.  Same quantity, different convention.)

    2. OpenVSP works in x aft / y right / z up; the plant uses standard body
       axes, x forward / y right / z down.  That is a 180 deg rotation about y,
       so x -> -x and z -> -z.  Under it P_xz is unchanged, while P_xy and P_yz
       both flip sign.  Moments of inertia are unaffected.
    """
    k = IN2M ** 2
    ixx, iyy, izz = r["Ixx"] * k, r["Iyy"] * k, r["Izz"] * k
    # products of inertia, rotated into body axes
    pxy, pxz, pyz = -r["Ixy"] * k, r["Ixz"] * k, -r["Iyz"] * k
    return {
        "Ixx": ixx, "Iyy": iyy, "Izz": izz,
        "Pxy": pxy, "Pxz": pxz, "Pyz": pyz,
        # inertia matrix entries: off-diagonals are the negated products
        "J": [[ixx, -pxy, -pxz], [-pxy, iyy, -pyz], [-pxz, -pyz, izz]],
    }


def inertia_report(r: dict) -> str:
    b = to_body_matrix(r)
    J = b["J"]
    out = [
        "\ndistributed inertia about the CG [kg m^2], body axes x fwd/y right/z down:",
        f"    moments  Ixx={b['Ixx']:.6e}  Iyy={b['Iyy']:.6e}  Izz={b['Izz']:.6e}",
        f"    products Pxy={b['Pxy']:.6e}  Pxz={b['Pxz']:.6e}  Pyz={b['Pyz']:.6e}",
        "",
        "MATLAB, for the 6DOF block (inertia MATRIX -- off-diagonals are -P):",
        f"  Inertia = [ {J[0][0]:.6e} {J[0][1]:+.6e} {J[0][2]:+.6e}",
        f"              {J[1][0]:+.6e} {J[1][1]:.6e} {J[1][2]:+.6e}",
        f"              {J[2][0]:+.6e} {J[2][1]:+.6e} {J[2][2]:.6e} ];",
    ]
    return "\n".join(out)


# --------------------------------------------------------------------------

def reference_check() -> None:
    """Reproduce the point-mass configuration and check the parse chain.

    Runs the model exactly as ``ft_explorer_sport.vspscript`` leaves it -- no
    shells, structure as a centreline point -- and asserts the published
    numbers come back.  If this fails, the parser or the OpenVSP version
    changed and every number below it is suspect.
    """
    print("reference pass: point-mass configuration (parser self-check)")
    d = WORK / "pass_ref"
    d.mkdir(parents=True, exist_ok=True)
    shutil.copy2(MODEL, d / MODEL.name)
    script = d / "pass_ref.vspscript"
    script.write_text(
        'void main()\n{\n    ClearVSPModel();\n'
        f'    ReadVSPFile( "{MODEL.name}" );\n'
        '    Update();\n'
        '    SetAnalysisInputDefaults( "MassProp" );\n'
        '    string rid = ExecAnalysis( "MassProp" );\n'
        '    PrintResults( rid );\n}\n', encoding="utf-8")
    proc = subprocess.run([str(VSPSCRIPT), "-script", script.name],
                          cwd=d, capture_output=True, text=True)
    (d / "run.log").write_text(proc.stdout + proc.stderr, encoding="utf-8")
    r = parse_massprops(d / f"{MODEL.stem}_MassProps.txt")

    expect = {"mass_kg": 0.8765, "Ixx": 3.189366973428757,
              "Iyy": 1.073061145509516e01, "Izz": 1.258557457032659e01,
              "Ixz": 1.814887933272729}
    bad = [f"{k}: got {r[k]!r}, expected {v!r}"
           for k, v in expect.items() if abs(r[k] - v) > 1e-6 * max(1.0, abs(v))]
    if bad:
        sys.exit("reference pass FAILED -- do not trust the results below:\n  "
                 + "\n  ".join(bad))
    print("    [PASS] reproduces the published point-mass tensor "
          "(Ixx 3.1894, Iyy 10.7306, Izz 12.5856, Pxz 1.8149 kg.in^2)")
    print("    [PASS] and the hand-computed parallel-axis sum of the 16 point "
          "masses gives Pxz = +1.8148, confirming OpenVSP reports products,")
    print("           not inertia-matrix entries.\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--structure-kg", type=float, default=STRUCTURE_KG,
                    help="structure mass the shells must total")
    ap.add_argument("--target-cg-mm", type=float, default=TARGET_CG_MM)
    args = ap.parse_args()

    if not VSPSCRIPT.exists():
        sys.exit(f"vspscript.exe not found at {VSPSCRIPT}")
    WORK.mkdir(exist_ok=True)

    reference_check()

    # ---- pass A: wetted areas ------------------------------------------------
    print("pass A: wetted areas (Mass_Area = 1)")
    a = run_pass("A", 1.0, 0.0, 0.0)
    areas = {g: a["components"][f"{g}"]["mass"] for g in SHELL_GEOMS
             if g in a["components"]}
    missing = set(SHELL_GEOMS) - set(areas)
    if missing:
        sys.exit(f"pass A: components missing from MassProps: {sorted(missing)}")
    total_area = sum(areas.values())
    sigma = args.structure_kg / total_area
    for g, v in areas.items():
        print(f"    {g:<26} {v:9.2f} in^2  ({100*v/total_area:4.1f}%)")
    print(f"    {'TOTAL':<26} {total_area:9.2f} in^2")
    print(f"  areal density = {sigma:.6e} kg/in^2 "
          f"= {sigma/IN2M**2*1000:.1f} g/m^2")

    # ---- pass B: everything but the battery ----------------------------------
    print("\npass B: calibrated shells, battery removed")
    b = run_pass("B", sigma, 0.0, 0.0)
    m_rest, x_rest = b["mass_kg"], b["cg_in"][0]
    print(f"    mass without battery {m_rest:.4f} kg, CG x {x_rest:.4f} in")

    x_target_in = WING_LE_IN + args.target_cg_mm / 25.4
    x_batt_in = (x_target_in * (m_rest + BATTERY_KG) - m_rest * x_rest) / BATTERY_KG
    x_batt_mm = (x_batt_in - WING_LE_IN) * 25.4
    print(f"    solved battery centre {x_batt_mm:+.2f} mm from wing LE "
          f"(model x {x_batt_in:.4f} in)")

    # ---- pass C: the answer --------------------------------------------------
    print("\npass C: battery at the solved station")
    c = run_pass("C", sigma, BATTERY_KG, x_batt_in)
    cg_mm = [(c["cg_in"][0] - WING_LE_IN) * 25.4,
             c["cg_in"][1] * 25.4, c["cg_in"][2] * 25.4]
    print(f"    total mass {c['mass_kg']:.4f} kg")
    print(f"    CG  x={cg_mm[0]:+.2f}  y={cg_mm[1]:+.2f}  z={cg_mm[2]:+.2f} mm "
          f"from wing LE")

    print(inertia_report(c))

    # ---- what changed --------------------------------------------------------
    k = IN2M ** 2
    b = to_body_matrix(c)
    print("\nagainst the point-mass model it replaces:")
    for nm, new, old in (("Ixx", b["Ixx"], 3.189366973428757 * k),
                         ("Iyy", b["Iyy"], 1.073061145509516e01 * k),
                         ("Izz", b["Izz"], 1.258557457032659e01 * k)):
        print(f"    {nm}  {old:.4e} -> {new:.4e}   ({new/old:5.2f}x)")
    print(f"    battery  -27.57 mm -> {x_batt_mm:+.2f} mm from wing LE "
          "(CG held on the 57 mm spec)")

    # A cross-check the calibration does not get for free: bare 3/16 in foam
    # board is about 250 g/m^2, so a structure that also carries spars, glue,
    # tape, hinges, horns and pushrods should land moderately above that.
    print(f"\n    areal density {sigma/IN2M**2*1000:.0f} g/m^2 against roughly "
          f"250 g/m^2 for bare 3/16 in board")
    print(f"    -> {sigma/IN2M**2*1000/250:.2f}x, i.e. glue/spar/hardware "
          "overhead, which is the expected direction and magnitude")


if __name__ == "__main__":
    main()
