"""Drive VSPAero cases for the FT Explorer low-speed coefficient build.

Every case runs in its own directory under ``raw/`` and keeps the generated
vspscript, the .vspaero setup file VSPAero actually consumed, and all solver
output.  Nothing is summarised in flight: the parser in build_tables.py reads
these files back, so any number in the final tables can be traced to a solver
output file on disk.

Control-surface deflections are applied by setting the DeflectionAngle parm of
the relevant VSPAero control-surface group.  Those parm IDs are read from
ft_explorer_aero.vsp3 rather than hard-coded, so rebuilding the model cannot
silently point the runner at the wrong surface.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import ft_explorer_conditions as C

HERE = Path(__file__).resolve().parent
VSP_DIR = Path(os.environ.get("OPENVSP_DIR", r"C:/OpenVSP-3.51.2-win64"))
VSPSCRIPT = VSP_DIR / "vspscript.exe"
AERO_MODEL = HERE / "ft_explorer_aero.vsp3"
RAW = HERE / "raw"

NCPU = 8

# VSPAero thin-surface set defined in ft_explorer_sport.vspscript.
THIN_SET = 3


def control_parms(model: Path = AERO_MODEL) -> dict[str, dict[str, str]]:
    """Recover {group name: {parm name: parm id}} from the saved model XML.

    OpenVSP does not expose control-surface groups through FindContainer, but it
    does persist their parm IDs in the .vsp3, and those IDs are stable across
    loads of the same file.
    """
    xml = model.read_text(encoding="utf-8", errors="ignore")
    groups: dict[str, dict[str, str]] = {}
    for blk in re.findall(r"<Control_Surface_Group>.*?</Control_Surface_Group>", xml, re.S):
        name = re.search(r"<Name>(.*?)</Name>", blk).group(1)
        parms = {m.group(1): m.group(3) for m in re.finditer(r'<(\w+) Value="([^"]+)" ID="(\w+)"/>', blk)}
        groups[name] = parms
    missing = set(GROUPS) - set(groups)
    if missing:
        raise RuntimeError(f"control surface groups missing from {model}: {sorted(missing)}")
    return groups


GROUPS = ("AilL", "AilR", "ElvL", "ElvR", "Rud")

def surface_deflections(aileron: float = 0.0, elevator: float = 0.0, rudder: float = 0.0) -> dict[str, float]:
    """Per-surface deflections, in degrees, for one command on each axis.

    The Surf1 copy of a mirrored control surface deflects in the opposite
    physical sense to the same command on Surf0 (measured; see
    build_aero_model.vspscript).  Hence the signs below, which look inverted but
    are what actually produce a roll command on the ailerons and a pitch command
    on the elevator.

    SIGN CONVENTIONS, chosen to match the HL-20 tables so the new set can be
    compared against them directly:

      positive aileron  -> positive rolling moment  (Cl_da > 0)
      positive elevator -> nose-down pitching moment (Cm_de < 0)
      positive rudder   -> positive yawing moment   (Cn_dr > 0)
    """
    return {
        "AilL": -aileron,   # both same sign => physically antisymmetric => roll
        "AilR": -aileron,
        "ElvL": +elevator,  # opposite signs => physically symmetric => pitch
        "ElvR": -elevator,
        "Rud": +rudder,
    }


def _gain_parms(parms: dict[str, str]) -> list[str]:
    return [pid for nm, pid in parms.items() if nm.endswith("_Gain")]


def build_script(
    case: str,
    alphas: tuple[float, float, int],
    betas: tuple[float, float, int],
    deflections: dict[str, float],
    stability: bool = False,
) -> str:
    groups = control_parms()
    lines: list[str] = []

    for gname, angle in deflections.items():
        parms = groups[gname]
        lines.append(f'    SetParmVal( "{parms["DeflectionAngle"]}", {angle!r} );')
        for pid in _gain_parms(parms):
            lines.append(f'    SetParmVal( "{pid}", 1.0 );')

    set_parms = "\n".join(lines)
    a0, a1, na = alphas
    b0, b1, nb = betas

    return f"""// Generated by run_cases.py -- case: {case}
void main()
{{
    ClearVSPModel();
    ReadVSPFile( "ft_explorer_aero.vsp3" );
{set_parms}
    Update();

    SetAnalysisInputDefaults( "VSPAEROComputeGeometry" );
    SetIntAnalysisInput( "VSPAEROComputeGeometry", "GeomSet", {{ SET_NONE }} );
    SetIntAnalysisInput( "VSPAEROComputeGeometry", "ThinGeomSet", {{ {THIN_SET} }} );
    ExecAnalysis( "VSPAEROComputeGeometry" );

    SetAnalysisInputDefaults( "VSPAEROSweep" );
    SetIntAnalysisInput( "VSPAEROSweep", "GeomSet", {{ SET_NONE }} );
    SetIntAnalysisInput( "VSPAEROSweep", "ThinGeomSet", {{ {THIN_SET} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "RefFlag", {{ 0 }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "Sref", {{ {C.SREF_IN2} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "bref", {{ {C.BREF_IN} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "cref", {{ {C.CREF_IN} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "Xcg", {{ {C.XCG_IN} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "Ycg", {{ {C.YCG_IN} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "Zcg", {{ {C.ZCG_IN} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "MachStart", {{ {C.MACH:.6f} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "MachEnd", {{ {C.MACH:.6f} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "MachNpts", {{ 1 }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "ReCref", {{ {C.RE_CREF:.1f} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "AlphaStart", {{ {a0} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "AlphaEnd", {{ {a1} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "AlphaNpts", {{ {na} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "BetaStart", {{ {b0} }} );
    SetDoubleAnalysisInput( "VSPAEROSweep", "BetaEnd", {{ {b1} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "BetaNpts", {{ {nb} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "NCPU", {{ {NCPU} }} );
    SetIntAnalysisInput( "VSPAEROSweep", "Symmetry", {{ 0 }} );
    SetIntAnalysisInput( "VSPAEROSweep", "UnsteadyType", {{ {1 if stability else 0} }} );
    Update();
    ExecAnalysis( "VSPAEROSweep" );
    Print( "CASE_DONE {case}" );
}}
"""


def run_case(
    case: str,
    alphas: tuple[float, float, int],
    betas: tuple[float, float, int] = (0.0, 0.0, 1),
    deflections: dict[str, float] | None = None,
    stability: bool = False,
    force: bool = False,
) -> Path:
    deflections = deflections or surface_deflections()
    cdir = RAW / case
    # A stability run writes .stab and no .polar; a normal sweep the reverse.
    polar = cdir / ("ft_explorer_aero.stab" if stability else "ft_explorer_aero.polar")
    if polar.exists() and not force:
        print(f"  [skip] {case} (already solved)")
        return cdir

    cdir.mkdir(parents=True, exist_ok=True)
    shutil.copy(AERO_MODEL, cdir / AERO_MODEL.name)
    script = cdir / "case.vspscript"
    script.write_text(
        build_script(case, alphas, betas, deflections, stability),
        encoding="ascii",
    )

    log = subprocess.run(
        [str(VSPSCRIPT), "-script", "case.vspscript"],
        cwd=cdir,
        capture_output=True,
        text=True,
        timeout=7200,
    )
    (cdir / "run.log").write_text(log.stdout + "\n" + log.stderr, encoding="utf-8", errors="replace")

    if "Could not find" in log.stdout:
        bad = [l.strip() for l in log.stdout.splitlines() if "Could not find" in l]
        raise RuntimeError(f"{case}: VSPAero could not resolve a control surface:\n  " + "\n  ".join(bad[:3]))
    if not polar.exists():
        raise RuntimeError(f"{case}: no {polar.suffix} produced; see {cdir / 'run.log'}")

    verify_setup(cdir / "ft_explorer_aero.vspaero", deflections, case)

    if stability:
        n = sum(1 for l in polar.read_text().splitlines() if l.startswith("Base_Aero"))
        print(f"  [ok]   {case}: {n} stability points")
    else:
        n = sum(1 for _ in polar.read_text().splitlines()) - 3
        print(f"  [ok]   {case}: {n} solved points")
    return cdir


def verify_setup(
    vspaero: Path,
    deflections: dict[str, float],
    case: str,
) -> None:
    """Assert the setup file VSPAero consumed carries the intended gains/angles.

    VSPAero labels the control-group columns of its .stab output by input order
    while applying an internally permuted component order, so a mis-set gain is
    not visible in the derivative output.  The setup file is the authority on
    what was actually applied, and it is checked here rather than trusted.
    """
    text = vspaero.read_text().splitlines()
    try:
        i = next(k for k, l in enumerate(text) if l.startswith("NumberOfControlGroups"))
    except StopIteration:
        raise RuntimeError(f"{case}: no control group block in {vspaero}")

    k = i + 1
    seen: dict[str, tuple[list[float], float]] = {}
    while k + 3 < len(text) and not text[k].startswith("NumberofSurvey"):
        name = text[k].strip()
        gains = [float(g) for g in text[k + 2].split(",")]
        angle = float(text[k + 3])
        seen[name] = (gains, angle)
        k += 4

    for gname, angle in deflections.items():
        if gname not in seen:
            raise RuntimeError(f"{case}: group {gname} missing from setup file")
        gains, applied = seen[gname]
        if abs(applied - angle) > 1e-9:
            raise RuntimeError(f"{case}: {gname} deflection {applied} != requested {angle}")
        if gains != [1.0] * len(gains):
            raise RuntimeError(f"{case}: {gname} gains {gains}, expected all +1")
        if len(gains) != 1:
            raise RuntimeError(f"{case}: {gname} has {len(gains)} surfaces; groups must be single-surface")


if __name__ == "__main__":
    RAW.mkdir(exist_ok=True)
    if not AERO_MODEL.exists():
        sys.exit("ft_explorer_aero.vsp3 missing - run build_aero_model.vspscript first")
    which = sys.argv[1] if len(sys.argv) > 1 else "explore"

    if which == "explore":
        # Wide sweeps used only to locate the stall boundaries from the spanwise
        # loading.  Not a table source.
        print("exploratory sweeps (band-finding):")
        run_case("explore_alpha", alphas=(-14.0, 14.0, 29))
        run_case("explore_beta", alphas=(1.0, 1.0, 1), betas=(-20.0, 20.0, 41))

    elif which == "production":
        a0, a1 = C.ALPHA_MIN_DEG, C.ALPHA_MAX_DEG
        na = len(C.alpha_grid())
        b0, b1 = C.BETA_MIN_DEG, C.BETA_MAX_DEG
        nb = len(C.beta_grid())

        print(f"1. static grid  alpha {a0:+.0f}..{a1:+.0f} ({na}) x beta {b0:+.0f}..{b1:+.0f} ({nb}):")
        run_case("static_grid", alphas=(a0, a1, na), betas=(b0, b1, nb))

        print("2. damping derivatives (stability run):")
        d0, d1 = C.ALPHA_DAMPING_DEG[0], C.ALPHA_DAMPING_DEG[-1]
        run_case("damping", alphas=(d0, d1, len(C.ALPHA_DAMPING_DEG)), stability=True)

        print("3. control deflection sweeps (one surface at a time):")
        for axis in ("aileron", "elevator", "rudder"):
            for defl in C.CONTROL_DEFLECTIONS_DEG:
                tag = f"{defl:+.0f}".replace("+", "p").replace("-", "m")
                run_case(
                    f"ctrl_{axis}_{tag}",
                    alphas=(a0, a1, na),
                    deflections=surface_deflections(**{axis: defl}),
                )

    else:
        sys.exit(f"unknown case set: {which}")
